config/routes.rb
Todo::Application.routes.draw do
  resources :items

  resources :lists

  resources :user_sessions

  resources :users

  get "public/index"

  get "public/about"

  match '/login', :to => 'user_sessions#new'
  match '/logout', :to => 'user_sessions#destroy'

  match '/add_item/:id', :to => 'lists#edit_items_add', :as => "add_item"

    root :to => "public#index"

end

app/models/list.rb
class List < ActiveRecord::Base
    attr_accessible :name, :list_date, :description, :user_id, :assigned_to
  belongs_to :user
  has_many :items
end

# == Schema Information
#
# Table name: lists
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  list_date   :date
#  description :string(255)
#  user_id     :integer
#  assigned_to :integer
#  created_at  :datetime
#  updated_at  :datetime
#

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :require_user

  def index
    if current_user.admin?
      @lists = List.where(:user_id => current_user.id )
    else
    @lists = List.where(:assigned_to => current_user.id)
    end
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params[:list])
    @list.user_id = current_user.id
    if @list.save
      flash[:notice] = "Successfully created list."
      redirect_to @list
    else
      render :action => 'new'
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.items.build(params[:list][:items])
    if @list.update_attributes(params[:list])
      @list.save
      flash[:notice] = "Successfully updated list."
      redirect_to list_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    flash[:notice] = "Successfully destroyed list."
    redirect_to lists_url
  end

  def edit_items_add
    @list = List.find(params[:id])
    @list.update_attributes(params[:list])
    @list.items.build()

    render :edit
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
  <div class="group">
    <%= f.label :name, t("activerecord.attributes.list.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field' %>
  </div>

  <div class="group">
    <%= f.label :list_date, t("activerecord.attributes.list.list_date", :default => "List date"), :class => :label %>
    <%= f.date_select :list_date, :class => 'date_select' %>
  </div>

  <div class="group">
    <%= f.label :description, t("activerecord.attributes.list.description", :default => "Description"), :class => :label %>
    <%= f.text_field :description, :class => 'text_field' %>
  </div>

  <div class="group">
    <%= f.label :assigned_to, t("activerecord.attributes.list.assigned_to", :default => "Assigned to"), :class => :label %>
    <%= f.collection_select :assigned_to, User.where(:created_by == current_user.id), :id, :username %>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), lists_path, :class => "text_button_padding link_button" %>
</div>

app/views/lists/_list_item.html.erb
<tr>
  <td><%= object.text_field :name %></td>
  <td><%= object.text_field :quantity, :size => 3 %></td>
</tr>

app/views/lists/_sidebar.html.erb
<div class="block">
  <h3>Items</h3>
  <ul class="navigation">
    <li><a href="#">Add new item</a></li>    
  </ul>
  
</div>
<div class="block notice">
  <h3>Simple Block</h3>
  <%#= f.fields_for :items do |item| %>
    <table>
      <tr>
        <th><%#= item.label :name %></th>
        <th><%#= item.label :quantity %></th>
      </tr>
    </table>
        <%# end %>
  <%#= link_to t("web-app-theme.add_new", :default => "Add New"), add_item_path(@list.id) %>
  </div>

app/views/lists/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", lists_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_list_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_list_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> List</h2>
    <div class="inner">
      <%= form_for @list, :url => list_path(@list), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>      
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/lists/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", lists_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_list_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Lists</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
           <th>
            <%= t("activerecord.attributes.list.name", :default => t("activerecord.labels.name", :default => "Name")) %>
          </th>
          <th>
            <%= t("activerecord.attributes.list.description", :default => t("activerecord.labels.name"), :default => "Name") %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @lists.each do |list| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= link_to list.id, list_path(list) %>
          </td>
                    <td>
            <%= list.name %>
          </td>
          <td>
            <%= list.description %>
          </td>
                    <td>
            <%= list.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", list_path(list) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_list_path(list) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", list_path(list), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/lists/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", lists_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_list_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  List</h2>
    <div class="inner">
      <%= form_for :list, :url => lists_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/lists/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", lists_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_list_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", list_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.list.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @list.name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.list.list_date", :default => t("activerecord.labels.list_date", :default => "List date")) %>:</b>
          <%= @list.list_date %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.list.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</b>
          <%= @list.description %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.list.assigned_to", :default => t("activerecord.labels.assigned_to", :default => "Assigned to")) %>:</b>
          <%= @list.assigned_to %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_list_path(@list), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), list_path(@list), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>