config/routes.rb
Todo::Application.routes.draw do
  resources :items

  resources :lists

  resources :user_sessions

  resources :users

  get "public/index"

  get "public/about"

  match '/login', :to => 'user_sessions#new'
  match '/logout', :to => 'user_sessions#destroy'

  match '/add_item/:id', :to => 'lists#edit_items_add', :as => "add_item"

    root :to => "public#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>To do List</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/drastic-dark/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
  <!--[if IE]>
			<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
  <div id="container">
    <div id="header">
      <%if current_user %>
      <h1><%= link_to "To do List", lists_path %></h1>
      <% else %>
      <h1><a href="/">To do List</a></h1>
      <% end %>
      <div id="user-navigation">
        <ul class="wat-cf">
          <% if current_user %>
          <li><%= link_to t("web-app-theme.profile", :default => "Profile"), edit_user_path(current_user.id) %></li>
          <!--<li><a href="#"><#%= t("web-app-theme.settings", :default => "Settings") %></a></li>
          <li><a href="/logout" class="logout"><#%= t("web-app-theme.logout", :default => "Logout") %></a></li>-->
          <li><%= link_to t("web-app-theme.logout", :default => "Logout"), logout_path,:class => "logout" %></li>
          <% else %>
          <li><%= link_to t("web-app-theme.login", :default => "Login"), login_path, :class => "logout" %></li>
          <% end %>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf">
        <% if current_user %>
        <li class="first"><%= link_to t("web-app-theme.lists", :default => "Lists"), lists_path %></li>

        <% if current_user.admin == true %>
        <li><%= link_to t("web-app-theme.users", :default => "Users"), users_path %></li>
        <% end %>
        <% end %>              
            </ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> Mr. Bob Fly</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>